// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sspatbmijtgcfydnyrxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzcGF0Ym1panRnY2Z5ZG55cnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyODY0NzEsImV4cCI6MjA1Nzg2MjQ3MX0.33OUtpq4jnT1Ya71B5iSK3AgJugDyU5z7QnDOVUAGYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);